### ISSUE TITLE
Images not being set on Loupedeck Live device

### ISSUE THREAD

**Issue by dlicudi** [devleaks/python-loupedeck-live#2]
When running test.py it does find the device and works for the haptic feedback and setting button colours but the tests to display images do not seem to do anything.

Tested Loupedeck for node.js and can see the center buttons change when running one of the examples (https://github.com/foxxyz/loupedeck).

Tried different python versions (3.10, 3.11, 3.12) and also downgraded Pillow to 9.5 just in case.
Pillow (9.5.0)
pyserial (3.5)

Loupedeck Live (firmware version 0.2.11)

![IMG_3011](https://github.com/devleaks/python-loupedeck-live/assets/2129148/80a7f205-c00e-48cb-ab69-86755456eb24)

DEBUG:DeviceManager:list: listing ports..
DEBUG:DeviceManager:trying /dev/tty.wlan-debug..
DEBUG:DeviceManager:..added /dev/tty.wlan-debug
DEBUG:DeviceManager:trying /dev/tty.Bluetooth-Incoming-Port..
DEBUG:DeviceManager:..added /dev/tty.Bluetooth-Incoming-Port
DEBUG:DeviceManager:trying /dev/tty.usbmodem101..
DEBUG:DeviceManager:..added /dev/tty.usbmodem101
DEBUG:DeviceManager:list: ..listed
DEBUG:Loupedeck:__init__: connection opened
DEBUG:Loupedeck:is_loupedeck: None: trying..
DEBUG:Loupedeck:is_loupedeck: b''
DEBUG:Loupedeck:is_loupedeck: b''
DEBUG:Loupedeck:is_loupedeck: None: ..got 2 wrong answers, probably not a LoupedeckLive device, ignoring.
DEBUG:Loupedeck:__init__: connection opened
DEBUG:Loupedeck:is_loupedeck: None: trying..
DEBUG:Loupedeck:is_loupedeck: b''
DEBUG:Loupedeck:is_loupedeck: b''
DEBUG:Loupedeck:is_loupedeck: None: ..got 2 wrong answers, probably not a LoupedeckLive device, ignoring.
DEBUG:Loupedeck:__init__: connection opened
DEBUG:Loupedeck:is_loupedeck: None: trying..
DEBUG:Loupedeck:is_loupedeck: b'HTTP/1.1 101 Switching Protocols\r\n'
DEBUG:Loupedeck:is_loupedeck: b'Upgrade: websocket\r\n'
DEBUG:Loupedeck:is_loupedeck: b'Connection: Upgrade\r\n'
DEBUG:Loupedeck:is_loupedeck: b'Sec-WebSocket-Accept: ALtlZo9FMEUEQleXJmq++ukUQ1s=\r\n'
DEBUG:Loupedeck:is_loupedeck: b'\r\n'
DEBUG:Loupedeck:is_loupedeck: None: ..got a LoupedeckLive device
DEBUG:LoupedeckLive:_read_serial: starting
DEBUG:LoupedeckLive:start: read started
DEBUG:LoupedeckLive:_process_messages: starting
DEBUG:LoupedeckLive:start: process started
DEBUG:LoupedeckLive:start: started
DEBUG:LoupedeckLive:Device: None
DEBUG:LoupedeckLive:init: inited
DEBUG:DeviceManager:enumerate: added Loupedeck device at /dev/tty.usbmodem101
trying.. <Loupedeck.Devices.LoupedeckLive.LoupedeckLive object at 0x102e8f5c0>
SHORT
MEDIUM
LONG
LOW
SHORT_LOW
SHORT_LOWER
LOWER
LOWEST
DESCEND_SLOW
DESCEND_MED
DESCEND_FAST
ASCEND_SLOW
ASCEND_MED
ASCEND_FAST
REV_SLOWEST
REV_SLOW
REV_MED
REV_FAST
REV_FASTER
REV_FASTEST
RISE_FALL
BUZZ
RUMBLE5
RUMBLE4
RUMBLE3
RUMBLE2
RUMBLE1
VERY_LONG
WARNING:LoupedeckLive:set_brightness: brightness set to 0
DEBUG:Loupedeck:__del__: connection closed
DEBUG:Loupedeck:__del__: connection closed
DEBUG:PIL.TiffImagePlugin:tag: Make (271) - type: string (2) Tag Location: 22 - Data Location: 122 - value: b'Google\x00'
DEBUG:PIL.TiffImagePlugin:tag: Model (272) - type: string (2) Tag Location: 34 - Data Location: 130 - value: b'Pixel 2 XL\x00'
DEBUG:PIL.TiffImagePlugin:tag: Orientation (274) - type: short (3) - value: b'\x00\x01'
DEBUG:PIL.TiffImagePlugin:tag: XResolution (282) - type: rational (5) Tag Location: 58 - Data Location: 142 - value: b'\x00\x00\x00H\x00\x00\x00\x01'
DEBUG:PIL.TiffImagePlugin:tag: YResolution (283) - type: rational (5) Tag Location: 70 - Data Location: 150 - value: b'\x00\x00\x00H\x00\x00\x00\x01'
DEBUG:PIL.TiffImagePlugin:tag: ResolutionUnit (296) - type: short (3) - value: b'\x00\x02'
DEBUG:PIL.TiffImagePlugin:tag: Software (305) - type: string (2) Tag Location: 94 - Data Location: 158 - value: b'HDR+ 1.0.220943774n\x00'
DEBUG:PIL.TiffImagePlugin:tag: DateTime (306) - type: string (2) Tag Location: 106 - Data Location: 178 - value: b'2019:03:23 18:33:50\x00'
DEBUG:PIL.TiffImagePlugin:tag: ExifIFD (34665) - type: long (4) - value: b'\x00\x00\x00\xc6'
DEBUG:PIL.TiffImagePlugin:tag: Orientation (274) - type: short (3) - value: b'\x00\x01'
DEBUG:PIL.TiffImagePlugin:tag: XResolution (282) - type: rational (5) Tag Location: 34 - Data Location: 86 - value: b'\x00\x00\x00H\x00\x00\x00\x01'
DEBUG:PIL.TiffImagePlugin:tag: YResolution (283) - type: rational (5) Tag Location: 46 - Data Location: 94 - value: b'\x00\x00\x00H\x00\x00\x00\x01'
DEBUG:PIL.TiffImagePlugin:tag: ResolutionUnit (296) - type: short (3) - value: b'\x00\x02'
DEBUG:PIL.TiffImagePlugin:tag: Copyright (33432) - type: string (2) Tag Location: 70 - Data Location: 102 - value: <table: 35 bytes>
DEBUG:PIL.TiffImagePlugin:tag: ExifIFD (34665) - type: long (4) - value: b'\x00\x00\x00\x8a'
DEBUG:PIL.TiffImagePlugin:tag: Orientation (274) - type: short (3) - value: b'\x00\x01'
DEBUG:PIL.TiffImagePlugin:tag: XResolution (282) - type: rational (5) Tag Location: 34 - Data Location: 74 - value: b'\x00\x00\x00H\x00\x00\x00\x01'
DEBUG:PIL.TiffImagePlugin:tag: YResolution (283) - type: rational (5) Tag Location: 46 - Data Location: 82 - value: b'\x00\x00\x00H\x00\x00\x00\x01'
DEBUG:PIL.TiffImagePlugin:tag: ResolutionUnit (296) - type: short (3) - value: b'\x00\x02'
DEBUG:PIL.TiffImagePlugin:tag: ExifIFD (34665) - type: long (4) - value: b'\x00\x00\x00Z'
DEBUG:LoupedeckLive:_read_serial: terminated
DEBUG:LoupedeckLive:_process_messages: terminated
DEBUG:LoupedeckLive:stop: stopped
DEBUG:Loupedeck:__del__: connection closed

**Comment by dlicudi** [comment]
Seems to be a similar issue here https://github.com/foxxyz/loupedeck/issues/33

After changing bytes to x00M seeing some images on the grid but I think they need to be offset, centre by 60, right by 420?

![IMG_3013](https://github.com/devleaks/python-loupedeck-live/assets/2129148/2b84f098-2d90-478b-ab83-4cef8cabea61)

`
DISPLAYS = {
    KW_CENTER: {"id": bytes("\x00A".encode("ascii")), KW_WIDTH: 360, KW_HEIGHT: 270},  # "A"
    KW_LEFT: {"id": bytes("\x00L".encode("ascii")), KW_WIDTH: 60, KW_HEIGHT: 270},  # "L"
    KW_RIGHT: {"id": bytes("\x00R".encode("ascii")), KW_WIDTH: 60, KW_HEIGHT: 270},  # "R"
}

DISPLAYS = {
    KW_CENTER: {"id": bytes("\x00M".encode("ascii")), KW_WIDTH: 360, KW_HEIGHT: 270},  # "A"
    KW_LEFT: {"id": bytes("\x00M".encode("ascii")), KW_WIDTH: 60, KW_HEIGHT: 270},  # "L"
    KW_RIGHT: {"id": bytes("\x00M".encode("ascii")), KW_WIDTH: 60, KW_HEIGHT: 270},  # "R"
}
`

Adding the x offset in the test_image function seems to confirm correct alignment, see 3 images correctly aligned now.

    def test_image(self):
        # image = Image.new("RGBA", (360, 270), "cyan")
        with open("Assets/yumi.jpg", "rb") as infile:
            image = Image.open(infile).convert("RGBA")
            self.draw_image(image, display=KW_CENTER, x=60)
        with open("Assets/left.jpg", "rb") as infile:
            image = Image.open(infile).convert("RGBA")
            self.draw_image(image, display=KW_LEFT)
        with open("Assets/right.jpg", "rb") as infile:
            image = Image.open(infile).convert("RGBA")
            self.draw_image(image, display=KW_RIGHT, x=420)
        # image2 = Image.new("RGBA", (90, 90), "blue")
        # self.set_key_image(6, image2)

**Comment by devleaks** [comment]
Wow. There is someone actually using this code?
Well, this one is going to be very difficult to track, I ran my "tests" and here is the pic:
![IMG_8262](https://github.com/devleaks/python-loupedeck-live/assets/6030167/4170b8d5-c8c9-497e-9d4f-b0edf60998c2)
Looks ok to me.
Possible different firmware versions? (I have 0.2.5 up to date as now.)
I did not make up those offset, they must come from somewhere...
(I have a large package relying on this package and it works perfectly...)
Let's investigate a bit.

**Comment by dlicudi** [comment]
Would this large package be https://github.com/devleaks/cockpitdecks? :)

Firmware on mine is showing a newer version (0.2.11), would hazard a guess that the behaviour different may be due to this.

I get the impression that older firmware/hardware of loupedeck live/ct models seem to treat left/centre/right as different 'screens' whilst it is treated as one big screen in the newer versions?

<img width="724" alt="image" src="https://github.com/devleaks/python-loupedeck-live/assets/2129148/79debd5f-4ee7-4581-b280-821f67dac1a6">

![IMG_3021](https://github.com/devleaks/python-loupedeck-live/assets/2129148/c3925072-8d94-4459-abb3-352e6941702f)

**Comment by devleaks** [comment]
Hi,

When I change the following 

```
DISPLAYS = {
    KW_CENTER: {"id": bytes("\x00A".encode("ascii")), KW_WIDTH: 360, KW_HEIGHT: 270},  # "A"
    KW_LEFT: {"id": bytes("\x00L".encode("ascii")), KW_WIDTH: 60, KW_HEIGHT: 270},  # "L"
    KW_RIGHT: {"id": bytes("\x00R".encode("ascii")), KW_WIDTH: 60, KW_HEIGHT: 270},  # "R"
}
```

to

```
DISPLAYS = {
    KW_CENTER: {"id": bytes("\x00M".encode("ascii")), KW_WIDTH: 360, KW_HEIGHT: 270},  # "A"
    KW_LEFT: {"id": bytes("\x00M".encode("ascii")), KW_WIDTH: 60, KW_HEIGHT: 270},  # "L"
    KW_RIGHT: {"id": bytes("\x00M".encode("ascii")), KW_WIDTH: 60, KW_HEIGHT: 270},  # "R"
}
```

I have *exactly* the picture you sent me above.

From the picture of your Loupedeck Live device, I see you have a device VER 02.00.
I have a LoupedeckLive VER/ 01.40, not 02.00.

I have firmware 0.2.5 and it says it is up to date. You have 0.2.11 for device VER 02.00.
That's were there must be differences.

I have no time to adjust my code right now, but I would if I have a clear message from Loupedeck with changelogs and documentation of their "protocol". I certainly don't want to trial and error and reverse engineer theirs.

Pierre

**Comment by devleaks** [comment]
Right move is to get proper, precise description of protocol from Loupedeck.
P.

**Comment by dlicudi** [comment]
As a temporary workaround I've added a quick conditional block to offset x by 60 for the center display.

src/Loupedeck/Devices/LoupedeckLive.py:550

    def draw_image(self, image, display: str, width: int = None, height: int = None, x: int = 0, y: int = 0, auto_refresh: bool = True):
        if display == 'center':
            x = x + 60
        buff = PILHelper.to_native_format(display, image)
        self.draw_buffer(buff, display=display, width=width, height=height, x=x, y=y, auto_refresh=auto_refresh)

**Comment by devleaks** [comment]
Indeed, the large package is [Cockpitdecks](https://github.com/devleaks/cockpitdecks).

For our issues, let's see what other developers, for instance the Loupedeck/node.js developers, are going to do. They probably will face the same issues. I don't have access to a newer device to test anyway.

Is the screen resolution of your "newer" device the same? May be they simply used a newer, finer LCD screen underneath?

**Comment by dlicudi** [comment]
I think it's the same resolution but this seems to confirm that it has in fact changed from '3' screens to a single unified display. I had previously tested the node.js version and it worked on my model. 

Might be interesting if you tested your device with the node.js Loupedeck Live project as that could indicate not having to add logic to handle different hardware versions of the Loupedeck Live device.

https://github.com/foxxyz/loupedeck/issues/29
https://github.com/foxxyz/loupedeck/commit/33f056b68b6646685490642874e98d707c1535df

> These devices require drawing to be done with the same unified display '\x00M' in the same way as the 'Razer Stream Controller'.
> It is also worth noting that the same unified display behaviour does work on the v1.x loupedeck live when running firmware 0.2.5, so there is potential for keeping the code simpler to do the same for both. (I havent tried firmware 0.1)

**Comment by dlicudi** [comment]
> Indeed, the large package is [Cockpitdecks](https://github.com/devleaks/cockpitdecks).

I have [Cockpitdecks](https://github.com/devleaks/cockpitdecks) working with the modified python-loupedeck-live code.
 
![IMG_3047](https://github.com/devleaks/python-loupedeck-live/assets/2129148/36f1df06-da1f-41c3-ba09-950319ddfa97)

**Comment by devleaks** [comment]
Well, to be honest, there are several ways to get the image on the device. Physically, in all cases, I think there only is one screen (sized 480x270px). Logically, as you read, we can access three portions, left (60px wide), center (360px wide), and right screen (again 60px wide) as if they were 3 independent screens. 

In one of the tests/version/trial I made in the course of developments, I considered the screen to be a single 480x270px device, with 6 x 3 buttons (instead of 4x3), splitting the narrower side screens in 3 buttons. But in this case, there are other interaction-related complications. The device has indeed a single touch sensibility on the 480x270px surface as a whole.

Yes, I'll have a look at the node.js development to see what happens to my device.
 (I temporarily added a discord link on my profile page for faster interaction if you wish.)

**Comment by dlicudi** [comment]
Link doesn't seem to work for me but can send me a friend request on Discord (duane1023)

**Comment by devleaks** [comment]
OK. I added your code correction and it now seems to work ok.
Could you please test 1.4.0 on your newer device? Thanks.
P.

**Comment by dlicudi** [comment]
Just installed loupedeck-1.4.0 and ran cockpit decks, screen looks ok.

P.S. On the wiki https://devleaks.github.io/cockpitdecks-docs/Installation/ the link to the repo needs to be corrected:
python-loupedeck-loupedecklive.git > python-loupedeck-live.git

> To have Cockpitdecks manage Loupedeck devices, add
> 
> $ pip install
> git+https://github.com/devleaks/python-loupedeck-loupedecklive.git
